name: Build Docker Image - Indev

on:
    push:
        branches-ignore: ["main"]
        paths-ignore: ["**.md"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              with:
                platforms: 'linux/amd64,linux/arm64'
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Set docker tag dynamically
              run: |
                BRANCH="${GITHUB_REF##*/}"
                echo "TAG=${BRANCH}-beta" >> $GITHUB_ENV
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: jackbailey
                password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                push: true
                platforms: linux/amd64,linux/arm64
                tags: jackbailey/lynx:${{ env.TAG }},jackbailey/lynx:beta
