name: Build Docker Image - Indev

on:
    push:
        branches-ignore: ["main"]
        paths-ignore: ["**.md"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              with:
                platforms: 'arm64,arm'
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Set docker tag dynamically
              run: |
                BRANCH="${GITHUB_REF##*/}"
                echo "TAG=${BRANCH}-beta" >> $GITHUB_ENV
            - name: docker login
              env:
                  DOCKER_USER: jackbailey
                  DOCKER_PASS: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
              run: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASS
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                push: true
                tags: "jackbailey/lynx:$TAG,jackbailey/lynx:beta"
