name: Update copyright year(s) in license file

on:
  schedule:
    - cron: '0 3 1 1 *' # 03:00 AM on January 1
  workflow_dispatch:

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commitAuthorEmail: ${{ secrets.COMMIT_EMAIL }}
          gpgPrivateKey: ${{ secrets.gpgPrivateKey }}
          gpgPassphrase: ${{ secrets.gpgPassphrase }}
