name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.11
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: |
            src/pnpm-lock.yaml
            frontend/pnpm-lock.yaml
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
        working-directory: src
      - name: Lint Backend
        uses: jackbailey/action-eslint@eslint-command
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # optional
          working-directory: src
          extensions: 'js'
          annotations: true
          eslint-command: eslint
      - run: pnpm install --frozen-lockfile
        working-directory: frontend
      - name: Lint Frontend
        uses: sibiraj-s/action-eslint@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }} # optional
            working-directory: frontend
            extensions: 'js,vue'
            annotations: true
            eslint-command: eslint