name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.8.0
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Lint Backend
        uses: sibiraj-s/action-eslint@2e3213f837c945a07368d53e42f4c16453c02087
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # optional
          working-directory: src
          extensions: 'js'
          annotations: true
          use-npx: true
      - name: Lint Frontend
        uses: sibiraj-s/action-eslint@2e3213f837c945a07368d53e42f4c16453c02087
        with:
            token: ${{ secrets.GITHUB_TOKEN }} # optional
            working-directory: frontend
            extensions: 'js,vue'
            annotations: true
            use-npx: true
