name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Lint Backend
        uses: jackbailey/action-eslint@6494c60dd93dbb092144ca58dbf0ca14e85e4574
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # optional
          working-directory: src
          extensions: 'js'
          annotations: true
          use-npx: true
      - name: Lint Frontend
        uses: jackbailey/action-eslint@6494c60dd93dbb092144ca58dbf0ca14e85e4574
        with:
            token: ${{ secrets.GITHUB_TOKEN }} # optional
            working-directory: frontend
            extensions: 'js,vue'
            annotations: true
            use-npx: true