name: Build Docker Image - Production

on:
    push:
        branches: ["main"]
        paths-ignore: ["**.md"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              with:
                platforms: 'linux/amd64,linux/arm64'
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Get version
              run: |
                IFS='.' read -ra VERSION <<< "$(cat VERSION)"

                MAJOR="${VERSION[0]}"
                MINOR="${VERSION[0]}.${VERSION[1]}"
                PATCH="${VERSION[0]}.${VERSION[1]}.${VERSION[2]}"

                IMAGE=jackbailey/lynx
                DOCKER_TAGS="$IMAGE:$MAJOR,$IMAGE:$MINOR,$IMAGE:$PATCH,$IMAGE:latest,$IMAGE:beta"

                echo "DOCKER_TAGS=$DOCKER_TAGS" >> $GITHUB_ENV
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: jackbailey
                password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ${{ env.DOCKER_TAGS }}
